### ISSUE TITLE
escaping file sensitive characters for track names

### ISSUE THREAD

**Issue by flbn** [pjmp/sunny#4]
ok, so i can't actually tell if this is me being on a train and the wifi being terrible or if it's just these specific tracks but i did notice that the only songs that failed downloading when i was checking this tool out had `/` in the title. i would peruse through the code to see if you're sanitizing it or passing it in as a literal (unescaped) but like i said my network connection is so weak rn 🫠

ok so, i tried downloading this album:
- title: Enola Gay
- link: https://sellofisura.bandcamp.com/album/enola-gay

and then all tracks ended up downloading fine, save for the second one, which has a `/`
- title: Defensa​/​Cortar
- link: https://sellofisura.bandcamp.com/track/defensa-cortar

i figured it was my connection, so i moved on and tried to download it individually -> failed, tried to download the album again, failed once more. 

then, i went to download this single, which also has a `/` present in the title
- title: Manchester xx​/​xx​/​20 (improvised)
- link: https://blackcountrynewroad.bandcamp.com/track/manchester-xx-xx-20-improvised

that's when i figured it was likely a bug, even though my wifi is ass rn

**Comment by flbn** [comment]
same w this album: https://homeiswhere.bandcamp.com/album/the-whaler-2
for tracks
- 9/12
- everyday feels like 9/11

**Comment by flbn** [comment]
btw, back on better wifi so can take a look at the code now

**Comment by flbn** [comment]
fixed by: https://github.com/pombadev/sunny/pull/5

**Comment by mid-at-coding** [comment]
in case any proof that this is not an isolated incident is needed: 
![image](https://github.com/pombadev/sunny/assets/64973075/05b16cca-03c6-4abf-b227-0473c93a9901)

**Comment by flbn** [comment]
did you try any of the albums mentioned? would be a quick repro

**Comment by flbn** [comment]
have a feeling the space characters might be meddling w the Everything Is A Lot tracks

**Comment by flbn** [comment]
nvm, looks like your tracks are failing too? see Neurotic/Erotic, Pro/Con, etc failing in your screenshot

**Comment by flbn** [comment]
ahh nvm, thought you were saying it was an isolated incident. wonder how other projects got around that

**Comment by mid-at-coding** [comment]
yes, I was just showing that its not specific to your setup/album choice(past it having songs that have special chars). (in case there was any doubt)
